### ISSUE TITLE
Discord notification lacks player nicknames

### ISSUE THREAD

**Issue by kudbus** [outfittracker/outfittracker#14]
As in the title there is problem with getting list of players that participated in taking the base in Planetside. It is really important to my outfit, P0L, to keep tracking this information to manage and control progress to Outfit wars.

**Comment by outfittracker** [comment]
I'm struggling a bit with the API for that part, sometimes the players are not sent, i don't know why ; i will investigate further, thank you for your feedback :)

**Comment by kudbus** [comment]
You are welcome! I and guys from my outfit really appreciate your work,
outfit from cobalt also use it. It's great Just needs that small but
meaning fix. I will keep an eye on that case and if it will change I will
notice you! Be healthy and happy!

czw., 2 kwi 2020, 17:21 użytkownik outfittracker <notifications@github.com>
napisał:

**Comment by Qaztar** [comment]
Same situation with SKL, sometimes it shows (specifically it seems for Andvari Barracks and Andvari (is "Andvari" meaning the bio lab or the whole region?) it shows the names)

**Comment by outfittracker** [comment]
Partially fixed, the notification can now take 1 minute to be delivered to the discord channel

**Comment by Qaztar** [comment]
Hey OutfitTracker,

Is there any chance we could have the discord notification send more than
just 10-12 names and "others"? Like have it list all the names?

**Comment by outfittracker** [comment]
Hello, i changed the limit to 48 players displayed

**Comment by Qaztar** [comment]
Thanks so much!
