### ISSUE TITLE
Activity Filter

### ISSUE THREAD

**Issue by rafamem** [outfittracker/outfittracker#17]
First of all, congratulations on the new website, it is excellent!! Thank you very much for this contribution to the Planetside 2 community.

Please consider adding a filter to show only "high activity" outfits in this ranking https://www.outfit-tracker.com/ranking/infantry/emerald/vs#rank and that returns 50 records instead of 25 :-)

**Comment by outfittracker** [comment]
Thank you for your feedback
We are working on a better ranking which will exclude low activity outfits. No problem on extending to 50 results or more

**Comment by outfittracker** [comment]
Ranking now include 50 outfits, the rank is now based on median ELO score
