### ISSUE TITLE
Unsure of how to use Outfit Tracker discord bot

### ISSUE THREAD

**Issue by Qaztar** [outfittracker/outfittracker#19]
In the discord, I type !track start SKL and the bot says "OK, i'm now tracking [SKL]" but it doesn't do anything after this (like pop up with bases we've taken). How do I get it to show these things?

**Comment by Qaztar** [comment]
Hmm, seems to work in my private testing discord. Lemme fiddle around with a few things

**Comment by outfittracker** [comment]
Hello, the bot is probably lacking some permissions to be able to talk (reply is a different thing), check in the server settings, you can maybe create a role for the bot, and enable all Text Permissions like Send message, embed links etc. Sometimes Discord create the role sometime not, not sure why

**Comment by Qaztar** [comment]
Fixed! Thanks
