### ISSUE TITLE
Outfit Tracker tracking a deleted outfit

### ISSUE THREAD

**Issue by Killeranator** [outfittracker/outfittracker#21]
So quick recap. Outfit name : Renegade 18 [R18].  First created on briggs then mainly moved to connery because of the shutdown of briggs but the outfit was split in two between soltech and connery.  Daybreak since told us they deleted the old outfit and we had to create a new one.  When we try to track this new outfit which has the same tag, the software tracks the deleted outfit that no one can apply for, as it is not in the database.  Tried updating the outfit via the force update but nothing worked.  First link is the new outfit and the second link is the deleted outfit.
https://www.outfit-tracker.com/outfit/renegade18-37570391403474619
https://www.outfit-tracker.com/outfit/renegade18-37517869661561646

**Comment by outfittracker** [comment]
I've deleted manually the old outfit, you should be able to track the new one

**Comment by outfittracker** [comment]
TODO: Handle outfit removal with the APÏ

**Comment by Killeranator** [comment]
everything all good now. Cheers mate
