### ISSUE TITLE
Cannot claim NSO Character

### ISSUE THREAD

**Issue by AdmiralParallax** [outfittracker/outfittracker#25]
When ever i try to claim my NSO character TheAdm1ral and link it to my outfit tracker account. It doesn't recognize when i log in, i have tried this many times. I have even reset the game and waited a week to see if it was a ongoing bug that would be fixed. A week later and nothing. 
My email is yangrose12@gmail.com

**Comment by outfittracker** [comment]
I'm going to investigate, i never tried claiming a nso character

**Comment by outfittracker** [comment]
Fixed with #28
