### ISSUE TITLE
Outfit Tracker showing outfit twice.

### ISSUE THREAD

**Issue by djohnson2390** [outfittracker/outfittracker#27]
My outfit has two listings

This one which is correct
https://www.outfit-tracker.com/outfit/restrainingorder-37573720558854196 

And this one which is incorrect and showing dead
https://www.outfit-tracker.com/outfit/restrainingorder-37573720558841910

Is it possible to remove the incorrect one as it is causing the discord bot to not track correctly.

**Comment by outfittracker** [comment]
Should be fixed definitively
