### ISSUE TITLE
Can't add/claim any of my characters

### ISSUE THREAD

**Issue by AerroBE** [outfittracker/outfittracker#28]
When I open the page to claim a certain character and log into the game on that specific character the website just keeps counting down until the timer is up. This happens on all my characters. I've tried getting an xp tick in game to see if that would do it but nope.

**Comment by outfittracker** [comment]
I will investigate this week end

**Comment by outfittracker** [comment]
Can you give your character name please ? Or contact me on discord Midd#0434

**Comment by outfittracker** [comment]
Server selection to prevent duplicate player name between PC and PS4
