### ISSUE TITLE
Not Working After Server Maintenance 

### ISSUE THREAD

**Issue by Coggernaut** [outfittracker/outfittracker#31]
After Server Maintenance, the outfit tracker's functions are not working. It's frozen on whatever was on April 19th (Pre-Update)

**Comment by outfittracker** [comment]
Some APIs are still down after the maintenance
Outfit Tracker rely heavily on the websocket API ; the server seems to be down (timeout)

Not much i can do, we'll have to wait until RPG fix it

**Comment by outfittracker** [comment]
API is up, everything should be running again
