### ISSUE TITLE
Bot is now responding to every single command that uses "!"

### ISSUE THREAD

**Issue by FTL-User-Ice** [outfittracker/outfittracker#32]
In one of my discord servers, we have more than one bot that uses the ! prefix for commands. The tracker bot is now responding to every single command that we use, even if it's got nothing to do with the outfit tracker bot. Is this intended?
![image](https://user-images.githubusercontent.com/7762643/115716999-b21fea00-a371-11eb-9984-5db125605384.png)

**Comment by outfittracker** [comment]
Fixed !
