### ISSUE TITLE
Player kills are counted incorrectly

### ISSUE THREAD

**Issue by Georgiks** [outfittracker/outfittracker#33]
![killboard](https://user-images.githubusercontent.com/19236717/116904433-f64a9e80-ac3d-11eb-8752-5348b532be7f.png)
![stats](https://user-images.githubusercontent.com/19236717/116904445-fb0f5280-ac3d-11eb-86e5-c636eb0ca765.png)

As you can see, number of kills does not match reality. Also that results in HSR being more than 100%.
Just a note, Infantry kills correctly reports 4.

**Comment by outfittracker** [comment]
Sorry for the late response, i will investigate the HSR > 100 is indeed very strange

**Comment by outfittracker** [comment]
I've coded a speculative fix, i keep an eye on that
