### ISSUE TITLE
Force update member doesn't work

### ISSUE THREAD

**Issue by boign** [outfittracker/outfittracker#34]
My outfit had over 1200 members, and now it only has 120.

The outfit player listing continues to show players who are no longer members. Even after forcing the update

The same happens when calculating the % activity of the outfit.

Example:
https://www.outfit-tracker.com/outfit/adrenalinebr-37510184933832476

![print1](https://user-images.githubusercontent.com/82240770/121092526-108a1600-c7c2-11eb-89c5-5c942ff79249.png)
![print2](https://user-images.githubusercontent.com/82240770/121092606-34e5f280-c7c2-11eb-8097-ef612d890371.png)

**Comment by outfittracker** [comment]
I've tried to fix the problem, but the API report me 338 members and not 120, still way better than 1200 ! Maybe there is some latency from the PS2 server, i will check in a few days if things corrected themselves.
Anyway thank you for the precise bug report

**Comment by outfittracker** [comment]
My bad, 120 members it is, it's fixed !

**Comment by boign** [comment]
Thank you for the great work for the community
